NAME=jack@cwi.nl
MAILTO=jack@cwi.nl
PATH=/Users/jack/bin:/usr/local/bin:/usr/bin:/bin:/sbin
20 23 * * * sh $HOME/src/ambulant/scripts/nightlybuild/nightlyrun.clean.sh
20 0 * * * sh $HOME/src/ambulant/scripts/nightlybuild/nightlyrun.mac.sh
20 1 * * * prlctl start Win7-VS2010-Nightly
20 2 * * * sh $HOME/src/ambulant/scripts/nightlybuild/nightlyrun.iphone.sh
20 3 * * * prlctl start Ubuntu-1110-32bit
20 5 * * * prlctl start Ubuntu-1110-64bit
