#ifndef AMBULANT_GUI_D2_WMUSER_H
#define AMBULANT_GUI_D2_WMUSER_H

#define WM_SET_CLIENT_RECT WM_USER+1
#define WM_UPDATE_VIEWPORT WM_USER+2
#define WM_REPLACE_DOC WM_USER+3
#define WM_AMBULANT_MESSAGE WM_USER+4
#endif // AMBULANT_GUI_D2_WMUSER_H
